### ISSUE TITLE
Undistort is distorting even more

### ISSUE THREAD

**Issue by wirmachenbunt** [vvvv/VL.OpenCV#7] opened 2018-10-18 14:44 UTC
Thoroughly tried the camera calibration example and it seems like the undistort node is distorting the image even more instead of doing the opposite.

I managed to get a reprojection error of 0.38, so pretty good. But applying this result with the undistort node gives you even more distorted corners and you get black pixels on the edges, as if the distortion is inverted.

**Comment by ravazquez** [comment] 2018-10-18 17:07
Could you check if you have inverted the width and height of your chessboard? This can cause issues similar to the ones you are describing.

**Comment by wirmachenbunt** [comment] 2018-10-18 18:18
i used the exact same checkerboard as required in the example 11x8. 

i did the same intrinics test with the same board with the old imagepack and the undistort shader and got a complete different visual result. so something is odd. didnt manage to achieve the same reprojection error with the imagepack. 

anyway, distorting the image more than before doesnt make sense.

**Comment by ravazquez** [comment] 2019-02-01 18:45
@wirmachenbunt We are tracking this down and need more information, can you tell us what camera you are using, provide us with the patch and also write out your Intrinsics and upload them here please?

**Comment by ravazquez** [comment] 2020-12-18 14:15
Closing this since I cannot reproduced and have had no feedback in almost a year

**Closed as completed by ravazquez** 2020-12-18 14:15 UTC
Labels: bug, feedback required
